version: '3.7'

services:
  paulweb:
    image: serverlein/lyrics-analytics:latest
    restart: always
    networks:
      traefik-public:
    deploy:
      update_config:
        parallelism: 2
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.lyrics-analytics.rule=Host(`lyrics.serverlein.de`)"
        - "traefik.http.routers.lyrics-analytics.entrypoints=websecure"
        - "traefik.http.routers.lyrics-analytics.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.lyrics-analytics.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true
