name: Webapp Docker Build and Push

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.7.0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./src/webapp
          push: true
          tags: serverlein/lyrics-analytics:latest
      -
        name: Get Portainer Token
        id: portainerTokenRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ secrets.PORTAINER_DOMAIN }}/api/auth'
          method: 'POST'
          data: '{"password":"${{ secrets.PORTAINER_PASS }}","username":"${{ secrets.PORTAINER_USER }}"}'
      -
        name: Portainer Redeploy
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ secrets.PORTAINER_DOMAIN }}/api/stacks/${{ secrets.PORTAINER_STACKID }}/git/redeploy?endpointId=2'
          method: 'PUT'
          timeout: 25000
          bearerToken: '${{ fromJson(steps.portainerTokenRequest.outputs.response).jwt }}'
          data: '{"env":[],"prune":false,"pullImage":true,"repositoryAuthentication":true,"repositoryPassword":"${{ secrets.PORTAINER_REPOPASS }}","repositoryReferenceName":"refs/heads/main","repositoryUsername":"JohannesBauer97"}'
